name: build independent jobs
on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: testing backend
        run: echo "Testing backend"
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: testing frontend
        run: echo "Testing frontend"