name: final challenge
on: 
  pull_request:

  branches:
    - main

jobs: 
  final-challenge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
        env:
          PROJECT_NAME: ZeroOps Production
        run: |
          echo "Setting up Python environment for $PROJECT_NAME"
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
      - name: Success
        run: echo "All tests passed successfully!"
