name: dependecies between jobs
on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: testing backend
        run: echo "Backend tests passing"
  frontend:
    needs: backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: testing frontend
        run: echo "Building frontend after backend success"