name: action secrets
on: push

jobs: 
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print secret length
        env:
          API_SECRET: ${{ secrets.API_KEY }}
        run: echo "Key length: ${#API_SECRET}"