name: action secrets
on: push

jobs: 
  secret:
    env:
      MY_SECRET: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print secret
        run: echo "Key length: ${#MY_SECRET}"